mysql:
  image: mysql
  container_name: "mysql-petclinic"
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic

mongo:
  image: mongo
  container_name: "mongodb-petclinic"
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    - MONGO_USER=root
    - MONGO_PASS=root
  ports:
    - 27017:27017

